### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by Rudloff** [WeAreFairphone/FP2-Checkup#2]
How should we number releases? Do we follow upstream and use something like `standalone-18.04.1`?

Edit: I just saw Fairphone now uses semantic version numbers like 2.1.8 (but don't tag them) so I guess we can use that as well.

**Comment by Rudloff** [comment]
@Roboe Any opinion on this?

**Comment by licaon-kter** [comment]
Does this have an actual app activity? I was able to use it via [QuickShortcut](https://play.google.com/store/apps/details?id=com.sika524.android.quickshortcut) but I was expecting an icon in the launcher.

**Comment by Rudloff** [comment]
Which commit did you build?
The launcher activity was added here: https://github.com/WeAreFairphone/FP2-Checkup/commit/861f0ea54d76a8ca3b660d29f9b5a2a9a04b5d17#diff-c8cc2dd42271f2bf39c6aa81eb6a5529R52

**Comment by Roboe** [comment]
@Rudloff Hmmm, I don't really have a preference

@licaon-kter Open a new issue, please

**Comment by Rudloff** [comment]
@Roboe I will use the APK version name in tags then, it makes F-Droid packaging easier.

**Comment by licaon-kter** [comment]
@Rudloff Right, that's better

Regarding F-Droid, I'll remove `compile 'com.google.android.gms:play-services-appindexing:8.1.0'` in the metadata, is the app still ok?

**Comment by Rudloff** [comment]
@licaon-kter I did not see that, thanks! The library does not seem to be used anywhere so I removed it.

I would say we are ready for a first release now.

**Comment by Rudloff** [comment]
I published the 2.1.8 tag: https://github.com/WeAreFairphone/FP2-Checkup/releases/tag/2.1.8
